import enum

BATCH_SIZE = 150


class Headers(enum.Enum):
    """A collection of CSV headers"""
    RESTAURANT_CODES = "CAMIS"
    RESTAURANT_NAME = "DBA"
    BUILDING = "BUILDING"
    BORO = "BORO"
    STREET = "STREET"
    ZIP_CODE = "ZIPCODE"
    PHONE = "PHONE"
    RESTAURANT_TYPES = "CUISINE DESCRIPTION"
    INSPECTION_TYPE = "INSPECTION TYPE"
    INSPECTION_DATE = "INSPECTION DATE"
    INSPECTION_SCORE = "SCORE"
    VIOLATION_CODE = "VIOLATION CODE"
    VIOLATION_DESCRIPTION = "VIOLATION DESCRIPTION"
    CRITICAL_RATING = "CRITICAL FLAG"
    GRADE_DATE = "RECORD DATE"
    GRADES = "GRADE"
