# Generated by Django 2.2.1 on 2019-05-31 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(max_length=100)),
                ('inspection_date', models.DateField(null=True)),
                ('score', models.PositiveSmallIntegerField(null=True)),
                ('grade_date', models.DateField(null=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('critical_rating', models.PositiveSmallIntegerField(choices=[(0, 'NOT_APPLICABLE'), (1, 'NOT_CRITICAL'), (2, 'CRITICAL')])),
                ('description', models.CharField(max_length=100)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Inspection')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boro', models.CharField(choices=[('bronx', 'BRONX'), ('brooklyn', 'BROOKLYN'), ('manhattan', 'MANHATTAN'), ('staten-island', 'STATEN_ISLAND'), ('queens', 'QUEENS')], max_length=25, null=True)),
                ('building_number', models.PositiveSmallIntegerField(null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=7, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.RestaurantType'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
