# Generated by Django 2.2.1 on 2019-06-02 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.InspectionType'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Inspection'),
        ),
    ]
