# Generated by Django 2.2.1 on 2019-06-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20190602_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcontact',
            name='building_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
