# Generated by Django 2.2.1 on 2019-06-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20190602_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttype',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restauranttype',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='violation',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
