# Generated by Django 2.2.1 on 2019-06-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20190603_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='code',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
